Repository mcci-catena/arduino-lmic, pull requests merged in 2018-09, with the labels that each got.

#97 Remove duplicate break
  examples/ttn-otaa/ttn-otaa.ino
Labels: bug

#107 Fix #101: clean up library.properties
  library.properties
Labels: enhancement

#113 Fix formatting in README.md
  README.md
Labels: docs
