Repository mcci-catena/arduino-lmic, pull requests merged in 2019-09, with the labels that each got.

#396 bugfix: add missing pinmode initialization in hal_interrupt_init()
  src/hal/hal.cpp
Labels: bug

#406 Improve EU868 compliance
  src/lmic/lmic.c
  src/lmic/lmic.h
  src/lmic/lmic_as923.c
  src/lmic/lmic_eu868.c
  src/lmic/lmic_eu_like.c
  src/lmic/lmic_in866.c
  src/lmic/lmic_kr920.c
Labels: bug

#412 Fix remaining failures in US V1.0.2 compliance
  HOWTO-ADD-REGION.md
  README.md
  doc/LMIC-v2.3.docx
  doc/LMIC-v2.3.pdf
  doc/LMIC-v3.0.99.docx
  doc/LMIC-v3.0.99.pdf
  examples/compliance-otaa-halconfig/compliance-otaa-halconfig.ino
  src/lmic/lmic.c
  src/lmic/lmic.h
  src/lmic/lmic_as923.c
  src/lmic/lmic_au921.c
  src/lmic/lmic_bandplan.h
  src/lmic/lmic_bandplan_as923.h
  src/lmic/lmic_bandplan_au921.h
  src/lmic/lmic_bandplan_eu868.h
  src/lmic/lmic_bandplan_in866.h
  src/lmic/lmic_bandplan_kr920.h
  src/lmic/lmic_bandplan_us915.h
  src/lmic/lmic_compliance.c
  src/lmic/lmic_eu868.c
  src/lmic/lmic_eu_like.c
  src/lmic/lmic_in866.c
  src/lmic/lmic_kr920.c
  src/lmic/lmic_us915.c
  src/lmic/lorabase.h
Labels: enhancement

#422 Fix #421: library.properties to v3.0.99; fix README nits.
  README.md
  library.properties
Labels: docs, release

#443 Compliance check improvements and bug fixes
  .travis.yml
  README.md
  examples/compliance-otaa-halconfig/compliance-otaa-halconfig.ino
  examples/ttn-otaa-feather-us915-dht22/ttn-otaa-feather-us915-dht22.ino
  examples/ttn-otaa-feather-us915/ttn-otaa-feather-us915.ino
  examples/ttn-otaa-halconfig-us915/ttn-otaa-halconfig-us915.ino
  examples/ttn-otaa-network-time/ttn-otaa-network-time.ino
  examples/ttn-otaa/ttn-otaa.ino
  src/lmic/lmic.c
  src/lmic/lmic.h
  src/lmic/lmic_as923.c
  src/lmic/lmic_bandplan.h
  src/lmic/lmic_bandplan_as923.h
  src/lmic/lmic_bandplan_eu868.h
  src/lmic/lmic_bandplan_in866.h
  src/lmic/lmic_bandplan_kr920.h
  src/lmic/lmic_compliance.c
  src/lmic/lmic_compliance.h
  src/lmic/lmic_eu868.c
  src/lmic/lmic_eu_like.c
  src/lmic/lmic_eu_like.h
  src/lmic/lmic_in866.c
  src/lmic/lmic_kr920.c
  src/lmic/oslmic.h
  src/lmic/radio.c
Labels: bug, enhancement

#452 Fix errors in US and AS923 tests (and AU915 implementation)
  README.md
  examples/compliance-otaa-halconfig/compliance-otaa-halconfig.ino
  src/lmic/lmic.c
  src/lmic/lmic.h
  src/lmic/lmic_as923.c
  src/lmic/lmic_au921.c
  src/lmic/lmic_compliance.c
  src/lmic/lmic_eu_like.c
  src/lmic/lorabase_as923.h
  src/lmic/lorabase_au921.h
Labels: bug
