Repository mcci-catena/arduino-lmic, pull requests merged in 2020-05, with the labels that each got.

#571 Remove interrupt disables; minor bug fixes
  .travis.yml
  README.md
  src/hal/hal.cpp
  src/lmic/hal.h
  src/lmic/lmic.c
  src/lmic/lmic.h
  src/lmic/lmic_compliance.c
  src/lmic/oslmic.c
  src/lmic/radio.c
Labels: Class A, bug, docs

#565 Add missing pinmap option
  src/hal/getpinmap_thisboard.cpp
Labels: bug

#572 Fix errors, omissions in examples.
  examples/raw/raw.ino
  examples/ttn-abp/ttn-abp.ino
  examples/ttn-otaa/ttn-otaa.ino
Labels: bug, enhancement
