Repository mcci-catena/arduino-lmic, pull requests merged in 2021-06, with the labels that each got.

#746 Fix #736: don't compile config objects that are for other platforms
  README.md
  src/hal/getpinmap_catena4420.cpp
  src/hal/getpinmap_feather32u4lora.cpp
  src/hal/getpinmap_featherm0lora.cpp
  src/hal/getpinmap_heltec_lora32.cpp
  src/hal/getpinmap_ttgo_lora32_v1.cpp
Labels: enhancement

#703 Warning message for feather 32u4 pin mapping
  examples/raw-feather/raw-feather.ino
  examples/ttn-otaa-feather-us915/ttn-otaa-feather-us915.ino
Labels: docs

#747 Fix #725: add link to @lnlp's LMIC-node application
  README.md
Labels: docs

#748 Bug fixes and doc improvements
  README.md
  src/lmic/lmic.c
  src/lmic/lmic.h
Labels: bug, docs

#764 Fix #763: use TimeLib.h in ttn-otaa-network-time example; this is v4.0.1-pre1
  README.md
  examples/ttn-otaa-network-time/ttn-otaa-network-time.ino
  src/lmic/lmic.h
Labels: bug
